// Code generated by ent, DO NOT EDIT.

package migration

import (
	"time"
)

const (
	// Label holds the string label denoting the migration type in the database.
	Label = "migration"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMigration holds the string denoting the migration field in the database.
	FieldMigration = "migration"
	// FieldExecutionAt holds the string denoting the execution_at field in the database.
	FieldExecutionAt = "execution_at"
	// Table holds the table name of the migration in the database.
	Table = "migrations"
)

// Columns holds all SQL columns for migration fields.
var Columns = []string{
	FieldID,
	FieldMigration,
	FieldExecutionAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultExecutionAt holds the default value on creation for the "execution_at" field.
	DefaultExecutionAt func() time.Time
)
