package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/tuoitrevohoc/app-template/backend/pkg/ent"
	"github.com/tuoitrevohoc/app-template/backend/pkg/ent/invoice"
	"github.com/tuoitrevohoc/app-template/backend/pkg/graph"
)

// CreateInvoice is the resolver for the createInvoice field.
func (r *mutationResolver) CreateInvoice(ctx context.Context, input ent.CreateInvoiceInput) (*ent.Invoice, error) {
	return r.Client.Invoice.Create().
		SetInput(input).
		Save(ctx)
}

// DeleteInvoice is the resolver for the deleteInvoice field.
func (r *mutationResolver) DeleteInvoice(ctx context.Context, id int) (*ent.Invoice, error) {
	invoice, err := r.Client.Invoice.Query().Where(
		invoice.IDEQ(id),
	).First(ctx)

	if err != nil {
		return nil, err
	}

	err = r.Client.Invoice.DeleteOneID(id).Exec(ctx)

	return invoice, err
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
