package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/tuoitrevohoc/app-template/api/ent"
	"github.com/tuoitrevohoc/app-template/api/pkg/logger"
	"go.uber.org/zap"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	log := logger.ForContext(ctx)
	log.Info("Resolving Node", zap.Int("nodeID", id))
	return r.Client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	log := logger.ForContext(ctx)
	log.Info("Resolving Node", zap.Ints("nodeIDs", ids))
	return r.Client.Noders(ctx, ids)
}

// Invoices is the resolver for the invoices field.
func (r *queryResolver) Invoices(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int) (*ent.InvoiceConnection, error) {
	return r.Client.Invoice.Query().Paginate(ctx, after, first, before, last)
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int) (*ent.PermissionConnection, error) {
	return r.Client.Permission.Query().Paginate(ctx, after, first, before, last)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int) (*ent.RoleConnection, error) {
	return r.Client.Role.Query().Paginate(ctx, after, first, before, last)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int) (*ent.UserConnection, error) {
	return r.Client.User.Query().Paginate(ctx, after, first, before, last)
}

// Query returns ent.QueryResolver implementation.
func (r *Resolver) Query() ent.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
