// Code generated by ent, DO NOT EDIT.

package ent

// CreateInvoiceInput represents a mutation input for creating invoices.
type CreateInvoiceInput struct {
	Title        string
	LeetCodeLink string
	InvoicedTo   string
}

// Mutate applies the CreateInvoiceInput on the InvoiceMutation builder.
func (i *CreateInvoiceInput) Mutate(m *InvoiceMutation) {
	m.SetTitle(i.Title)
	m.SetLeetCodeLink(i.LeetCodeLink)
	m.SetInvoicedTo(i.InvoicedTo)
}

// SetInput applies the change-set in the CreateInvoiceInput on the InvoiceCreate builder.
func (c *InvoiceCreate) SetInput(i CreateInvoiceInput) *InvoiceCreate {
	i.Mutate(c.Mutation())
	return c
}
