// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/tuoitrevohoc/app-template/api/ent/migration"
	"github.com/tuoitrevohoc/app-template/api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	migrationFields := schema.Migration{}.Fields()
	_ = migrationFields
	// migrationDescExecutionAt is the schema descriptor for execution_at field.
	migrationDescExecutionAt := migrationFields[1].Descriptor()
	// migration.DefaultExecutionAt holds the default value on creation for the execution_at field.
	migration.DefaultExecutionAt = migrationDescExecutionAt.Default.(func() time.Time)
}
