// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/tuoitrevohoc/app-template/api/app/bootstrap"
	"github.com/tuoitrevohoc/app-template/api/app/config"
	"github.com/tuoitrevohoc/app-template/api/app/resolvers"
)

// Injectors from wire.go:

func CreateServer() (*Server, error) {
	configurations, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.NewEntClient(configurations)
	if err != nil {
		return nil, err
	}
	resolver := resolvers.NewResolver(client)
	executableSchema := bootstrap.NewSchema(resolver)
	server := NewServer(executableSchema, configurations)
	return server, nil
}
